#!/bin/bash
yum update -y
yum install -y httpd24 php56 mysql55-server php56-mysqlnd
service httpd start
chkconfig httpd on
groupadd www
usermod -a -G www ec2-user
chown -R root:www /var/www
curl -o /var/www/index.html https://raw.githubusercontent.com/bopace/cs-462-user-script/master/index.html
chmod 2775 /var/www
